pipeline {
    agent any

    parameters{
        string(name: 'inp_str', defaultValue: 'Nada definido', description: 'Descricao')
        choice(name: 'tipo', choices: ['sub','mul','add','div'], description: 'tipo de operacao')
    }

    stages {
        stage('Stage 1: Echo parameter') {
            steps {
                bat 'echo ' + params.inp_str
            }
        }
        
    }

}