pipeline {
    agent any
    options {
            copyArtifactPermission('test')
    }

    stages {
        stage('Stage 1: Checkout SCM') {
            steps {
                checkout scm
            }
        }
        stage('Stage 2: Install Dependencies') {
            steps {
                script{
                    bat 'pip install pyinstaller'
                    bat 'pip install junit-xml'
                }
            }
        }
        stage('Stage 3: Compile') {
            steps {
                bat 'python -m py_compile main.py'
            }
        }
        stage('Stage 4: Create installer') {
            steps {
                bat 'pyinstaller --onefile main.py'
            }
        }
    }


    post {
        always{
            archiveArtifacts artifacts: 'dist\\main.exe',
            onlyIfSuccessful: true
        }

    }
}